### ISSUE TITLE
Make GCP Accounts and invite mizuno gcp accounts

### ISSUE THREAD

**Issue by Z-zia** [aonorito/aoview#11]
# Background

とりあえずフロントエンドをデプロイするサーバーを用意したい。
AWS or GCPで検討の結果、アカウント管理しやすいGCPにすることになった。
その前にGCPのアカウントを準備し、チームで開発できるようにする。

# Overview

GCPアカウントの作成

# Goal

- GCPアカウントの作成
- aoview project作成
- 水野を招待
- IAMで強めの権限付与

**Comment by Z-zia** [comment]
poker: 1h

**Comment by aonorito** [comment]
@Z-zia 
GCPにオーナー権限を付与しました。

**Comment by Z-zia** [comment]
@aonorito 
Thanks!!
