### ISSUE TITLE
Set template for issue of repository

### ISSUE THREAD

**Issue by Z-zia** [aonorito/aoview#4]
# Background

issue作成する際に、"Background"など入力するのが手間

# Overview

issue作成する際にテンプレ選択できるようにする（Githubの設定）

# Goal

- feature issueのテンプレ作成
- bug issueのテンプレ作成

**Comment by aonorito** [comment]
issue作成時に、「Feature request」と「Bug report」を選択できるようテンプレートを追加しました。
参考サイト：https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by Z-zia** [comment]
@aonorito 
bugは発生時刻とか再現するための条件とか、細かく書けたほうが良いかも

**Comment by aonorito** [comment]
@Z-zia 
bugテンプレートに、以下の項目を追加しました。
・発生時刻
・再現条件
・関連issue

**Comment by aonorito** [comment]
@Z-zia 
Feature requestテンプレートに、やらないことを記述する項目を追加しました。

**Comment by Z-zia** [comment]
@aonorito LGTM:rocket:
