### ISSUE TITLE
Write rule of frontend file tree to README.md

### ISSUE THREAD

**Issue by Z-zia** [aonorito/aoview#7]
# Overview

フロントエンドのディレクトリ構成について議論して、README.mdに追記する

# Goal

- フロントエンドのディレクトリ構成の決定

**Comment by aonorito** [comment]
- ルート
  - src
    - Top
      - page
      - ui
      - vuex(状態管理)
    - Next Screen
      - page
      - ui
      - vuex(状態管理)
    - 共通
      - ui

- ルート
  - src
    - page
      - top
      - next
    - ui
      - button
      - text 
    - vuex
      - ....

**Comment by Z-zia** [comment]
## mizuno案

- frontend/
  - images
    - xxx.png
  - javascripts
    - apis
    - components
      - pages
        - xxx.vue
      - parts
        - xxx_header.vue
        - xxx_button.vue
      - templates
        - xxx_templates.vue
    - models
      - user.ts
      - role.ts
      - ....
    - stores
      - xxx_stores.ts
    - util
      - xxx_util.ts
    - index.js
    - App.vue
    - router.js
  - stylesheets 
    - base.scss

**Comment by Z-zia** [comment]
一旦mizuno案で進めて都度改善する

**Comment by Z-zia** [comment]
@aonorito 
README.mdに記載よろ

**Comment by aonorito** [comment]
@Z-zia 
READMEにフロントのフォルダ構成を記載しました。
プルリクは下記です。
https://github.com/aonorito/aoview/pull/14

---
pushするときに聞かれるパスワードがアクセストークンだということをすっかり忘れてて、2日ほど無駄にした

**Comment by Z-zia** [comment]
@aonorito 

コードレビューはPRの右のこの2つ設定するだけで気づきますぜ
![image](https://user-images.githubusercontent.com/58901619/214568778-fc11cbe7-571f-4d61-8977-98b9af1e019c.png)


>pushするときに聞かれるパスワードがアクセストークンだということをすっかり忘れてて、2日ほど無駄にした

これ最初のうちはあるあるやでw
